name: KyaniteConsilium
version: '1.0.3'
main: com.maxstudios.kyaniteConsilium.Main
api-version: '1.21'
commands:
  kyaniteconsilium:
    description: "Shows plugin"
    aliases:
      - kc
      - consilium
      - kyanite
  clock:
    description: "Shows time in real format"
    aliases:
      - clock
      - clock-now
      - time-here
      - rtime
      - real-time

  about:
    description: "Shows my GitHub"
    aliases:
      - about-kyanite
      - kyanite-git
